# fly.toml app configuration file generated for backend-little-field-1648 on 2025-05-08T18:41:54+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-little-field-1648'
primary_region = 'lhr'

[processes]
  app = "java -Dhttps.protocols=TLSv1.2 -jar app.jar"
  # Changed from target/movies-0.0.1-SNAPSHOT.jar to app.jar

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[build]
  dockerfile = "Dockerfile"